[package]
name = "rusticata"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
crate-type = ["dylib"]
# crate-type = ["staticlib"]

[dependencies]
libc = "0.2.0"
nom = "1.2.4"

[dependencies.tls-parser]
path = "/home/pollux/CODE/RUST/tls-parser"
