[package]
name = "rusticata"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[lib]
crate-type = ["dylib"]
# crate-type = ["staticlib"]

[dependencies]
libc = "0.2.0"
log = "0.3.6"
nom = "1.2.4"
tls-parser = { git = "https://github.com/rusticata/tls-parser.git" }
